FROM centos:7
RUN curl -sSL -o ossfs_1.80.2_centos7.0_x86_64.rpm 39.107.105.58/ossfs_1.80.2_centos7.0_x86_64.rpm && \
	yum localinstall -y ossfs_1.80.2_centos7.0_x86_64.rpm && \
    rm -rf ossfs_1.80.2_centos7.0_x86_64.rpm
